id: P96D5DD2D
initial_creation_type: ocr
source_metadata:
  volumes:
    33283d15dfa448af93141fb06d5ada2a:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: གནས་ཆེན་པོ་བརྒྱད་ཀྱི་མཆོད་རྟེན་ལ་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
